# Perform other matrix operations like converting matrix data to absolute values, taking the negative of matrix values, additing/removing rows/columns from a matrix, finding the maximum or minimum values in a matrix or in a row/column, and finding the sum of all elements in a matrix.

To make any matrix absolute  we use absolute function from numpy module and pass the matrix.

In [7]:
import numpy as np
A = np.array([
[1, -2, 3],
[4,  5, 6],
[7, -8, 9]])
x=np.absolute(A)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
import numpy as np
A = np.array([
[1, -2, 3],
[4,  5, 6],
[7, -8, 9]])
x=np.delete(A,1,0)
print(x)

[[ 1 -2  3]
 [ 7 -8  9]]


In [25]:
import numpy as np
A = np.array([
[1, -2, 3],
[4,  5, 6],
[7, -8, 9]])
x=np.insert(A,[3],[10,11,12],axis=0)
print(x)

[[ 1 -2  3]
 [ 4  5  6]
 [ 7 -8  9]
 [10 11 12]]


In [26]:
import numpy as np
A = np.array([
[1, -2, 3],
[4,  5, 6],
[7, -8, 9]])
x=np.max(A)
print(x)

9


In [27]:
import numpy as np
A = np.array([
[1, -2, 3],
[4,  5, 6],
[7, -8, 9]])
x=np.min(A)
print(x)

-8


In [28]:
import numpy as np
A = np.array([
[1, -2, 3],
[4,  5, 6],
[7, -8, 9]])
x=np.sum(A)
print(x)

25
